### ISSUE TITLE
feature request: podcasts sync

### ISSUE THREAD

**Issue by sanzoghenzo** [tkem/mopidy-podcast-gpodder#1]
Hi,
I just installed this plugin on my music box. I overlooked the fact that as of now the plugin only lists podcast directories and doesn't sync my podcast subscription.
Do you have any plan to support that?
I really would like to be able to listen episodes at home and continue to do so outside with my phone (and vice versa) without having to remind which episodes I already listened to..
Thanks for the attention!

**Comment by tkem** [comment]
User authentication and subscriptions are currently not supported. Only the public, unauthenticated API is used. Although this is an interesting use case, I currently don't have any plans for supporting subscriptions, sorry.
